BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Cover> list = _unitOfWork.CoverType.GetAll();
            return View(list);
        }

        // GET method of Add new Cover Type.

        public IActionResult Create()
        {
            return View();
        }

        // POST method of Add new Cover Type
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Cover cover)
        {
            /*if (ModelState.IsValid)
            {*/
            _unitOfWork.CoverType.Add(cover);
            _unitOfWork.Save();
            TempData["success"] = "Cover Type Added Successfully!!!";
            return RedirectToAction("Index");
            /* }
             else
             {
                 return View();
             }*/
        }

        // GET method for Edit
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Cover cover = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (cover == null)
            {
                return NotFound();
            }
            return View(cover);
        }

        // POST method for Edit
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult EditPost(Cover cover)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(cover);
                _unitOfWork.Save();
                TempData["success"] = "Cover Type Updated Successfully!!!";

                return RedirectToAction("Index");
            }
            return View();
        }

        // GET method for Delete

        public IActionResult Delete(int id)
        {
            Cover cover = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            _unitOfWork.CoverType.Remove(cover);
            _unitOfWork.Save();
            TempData["success"] = "Cover Type Deleted Successfully!!!";

            return RedirectToAction("Index");
        }

    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model Cover
@{
    ViewData["Title"] = "Create";
}
<form method="post">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Cover Type</h2>
            <div class="border-3 w-100 bg-primary" style="height:2px"></div>

        </div>
        <div class="mb-3">
            <input asp-for="Id" hidden />
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" class=" form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button class="btn btn-outline-primary" type="submit" style="width:150px">Create</button>
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary">
            <i class="bi bi-arrow-left-circle"></i> &nbsp;
            Back to List
        </a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model Cover
@{
    ViewData["Title"] = "Edit";
}

<form method="post" asp-action="EditPost">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Cover Type</h2>
            <div class="border-3 w-100 bg-primary" style="height:2px"></div>
        </div>
        <div class="mb-3">
            <input asp-for="Id" hidden />
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" class=" form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button class="btn btn-primary" type="submit" style="width:150px">Update</button>
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary">
            <i class="bi bi-arrow-left-circle"></i> &nbsp;
            Back to List
        </a>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<Cover>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">

    <div class="row p-4">
        <div class="col-6">
            <h2 class="text-primary">
                Cover Type List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Add New Cover Type
            </a>
        </div>
    </div>

    <table class="table table-bordered table-striped" style="width:100%">
        @if (Model.Count() > 0)
        {
                <thead>
                    <tr>
                        <th>
                            Cover Type Name
                        </th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody>
                @foreach (var item in Model)
                {
                            <tr>
                                <td width="60%">
                            @item.Name
                                </td>
                                <td class="btn-group w-100" width="40%" role="group">
                                    <a class="btn btn-info m-0 w-50" asp-controller="CoverType" asp-action="Edit" asp-route-id="@item.Id"> <i class="bi bi-pencil-square"></i> &nbsp; Edit</a>
                                    <a class="btn btn-danger m-0 w-50" asp-controller="CoverType" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i> &nbsp; Delete</a>
                                </td>
                            </tr>
                }
                </tbody>
        }
        else
        {
                <h5 class="text-info">No Cover Type found! Add new Cover Type.</h5>
        }
    </table>
</div>